
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: outdoorne_development

test:
  <<: *default
  database: outdoorne_test

production:
  <<: *default
  database: outdoorne_production
  username: outdoorne
  password: <%= ENV['OUTDOORNE_DATABASE_PASSWORD'] %>
